steps:
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: 'azure-functions/**/*.csproj'
    
- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    arguments: '--configuration Release --no-restore'
    projects: 'azure-functions/**/*.csproj'
    
- task: DotNetCoreCLI@2
  displayName: Ping - dotnet publish
  inputs:
    command: publish
    arguments: 'azure-functions/ping/ping.csproj --configuration Release --no-restore --output $(Build.ArtifactStagingDirectory)/Release/ping'
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false
    
- task: DotNetCoreCLI@2
  displayName: Timer - dotnet publish
  inputs:
    command: publish
    arguments: 'azure-functions/timer/timer.csproj --configuration Release --no-restore --output $(Build.ArtifactStagingDirectory)/Release/timer'
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false
    
- task: DotNetCoreCLI@2
  displayName: Event Grid - dotnet publish
  inputs:
    command: publish
    arguments: 'azure-functions/eventgrid/eventgrid.csproj --configuration Release --no-restore --output $(Build.ArtifactStagingDirectory)/Release/eventgrid'
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false

- task: CopyFiles@2
  displayName: Ping - Copy ARM template to Build.ArtifactsStagingDirectory
  inputs:
    SourceFolder: 'azure-functions/ping'
    Contents: 'azuredeploy.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Release/ping'
    
- task: CopyFiles@2
  displayName: Timer - Copy ARM template to Build.ArtifactsStagingDirectory
  inputs:
    SourceFolder: 'azure-functions/timer'
    Contents: 'azuredeploy.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Release/timer'

- task: CopyFiles@2
  displayName: Event Grid - Copy ARM template to Build.ArtifactsStagingDirectory
  inputs:
    SourceFolder: 'azure-functions/eventgrid'
    Contents: | 
        azuredeploy.json
        azuredeploy-subscribe-event-grid.json
        get-function-host-mater-key.ps1
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Release/eventgrid'

    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/Release'
  condition: succeededOrFailed()
