name: 1.0$(Rev:.rr)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - azure-functions
    
stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    pool:
      name: Default
    steps:
    - template: "build.yaml"

stages:
- stage: deploy
  displayName: Deploy
  jobs:
  - deployment:
    displayName: Release
    pool:
      name: Default
    environment: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - template: "deploy.yaml"

