name: 1.0$(Rev:.rr)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - azure-functions
    
stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    pool:
      name: "Hosted VS2017"
    steps:
    - template: "build.yaml"

- stage: deploy
  displayName: Deploy
  jobs:
  - deployment:
    displayName: Release
    pool:
      name: "Hosted VS2017"
    environment: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - template: "deploy.yaml"
            parameters:
                serviceConnectionName: "subscription-service-connection"
                resourceGroupName: "function-apps-rg"
                location: "North Europe"
                functionStorageName: "function0apps0st"
                pingFunctionAppName: "ping-fa"
                timerFunctionAppName: "timer-fa"
                eventGridFunctionAppName: "event-grid-fa"
                

